language: node_js

node_js:
  - 10.13.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: yarn run build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

deploy:
  provider: npm
  email: $NPM_MAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
